### ISSUE TITLE
Setting up a cronjob

### ISSUE THREAD

**Issue by matsta10** [brutog/bettertron#7]
Hey there,

First off, this script is awesome! 

Anywho I want to run a cron to automate the task.

If I run the better.pl directly without cd'ing into the folder then it creates a better.ini in my home folder which doesn't work.

So I made a basic bash script as follows:
# ! /bin/bash

cd ~/bettertron/
perl better.pl

That works fine if I run the script in terminal, but when I add it to a cron, then it doesn't seem to work.

0,5,10,15,20,25,30,35,40,45,50,55 \* \* \* \* bash /home/matsta/bettertron/autotranscode.sh

I'm on a seedbox, so unfortunately I can't see the cron logs to see what the problem is.

If you could please help, that would be much appreciated!

Cheers,

**Comment by brutog** [comment]
chamunks suggestions sound good. maybe i'll add logging but i'd rather keep this as portable as possible for seedbox usage.
